# `numpy`
- one of the core packages for numerical computing in python
- many packages are built on top of numpy
- `numpy` has been optimized for processing: faster due to memory access

In [1]:
# import numpy with standard abbreviation
import numpy as np

# Variables
a name we assign to a particular object in Python. For example:

In [2]:
# assign a small array to a variable a
a = np.array( [ [1,1,2], [3,5,8] ] )

When we run the cell, we store the variable and its value. We can see the variable's value in two ways:

In [3]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
print(a)

[[1 1 2]
 [3 5 8]]


## naming variables
in the class, we are going to use `snake_case` for naming variables. 

# Variables and objects

**object**: often encountered in Python documentation and tutorials. 

object is a bundle of properties and actions about something specific.

Example:

- object: data frame
    - properties: number of rows, names of columns, data created
    - actions: selecting a row, adding a column, ...
    
A variable is a name we give a specific object, and the same object can be referenced by different variables.

Example:

- The Sun (the actual star at the center of the solar system = object
- sol = Spanish word for Sun = variable
- soleil = French for Sun = another variable

In practice, we will use object and variable interchangeably.

# Types

Each object in Python has a type.

type = what kind of object it is

We can also call the type of the object the **class** of the object.

We can see the type/class of an object by using the `type` function:

In [6]:
print(a)
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

The `numpy.ndarray` is the core object/data type in the NumPy package. We can check the type of an entry in the array by indexing:

In [7]:
print(a[0,0])
type(a[0,0])

1


numpy.int64

In [8]:
# how would you access the value 5 in the array a?
print(a[1,1])

5


# Functions

`print` was our example of a python function! :))

A function:
- take in a set of **arguments** separated by commas, and 
- use those arguments tot produce some **outputs**

argument = parameter : you might see argument more often in the documentation

We can ask information about a function by executing `?` followed by the function name:

In [9]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


- first line: function showing all of its arguments in ()
- then a short description of what the function does
- finally, a list of the arguments and a brief explanation of each of them.

Different types of arguments inside the parenthesis. Roughly speaking, there are two types of arguments:

- **non-optional arguments**: arguments you need to specify for function to do something
- **optional arguments**: arguments that are pre-filled with a default value by the function, but we can override them. Optional arguments appear inside the parenthsis in the form 

`optional argument = default_value`

In [11]:
print('changing the default end argument of the print function', end=' :)')

changing the default end argument of the print function :)

In [12]:
print('changing the default end argument of the print function')

changing the default end argument of the print function
